name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # every weekday
    - cron: '0 0 * * 1-5'
    # every sunday (no-cache)
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      no-cache:
        description: 'Skip Docker cache'
        type: boolean
        default: false

env:
  IMAGE: articulate/articulate-ruby

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        tag:
          - 2.7-buster-slim
          - 2.7-buster-slim-minimal
          - 2.7-buster-slim-qt
          - 2.7-bullseye-slim
          - 2.7-bullseye-slim-qt
          - 3.1-bullseye-slim
          - 3.1-bullseye-slim-minimal
          - 3.1-bullseye-slim-qt
          - 3.2-bullseye-slim
          - 3.2-bullseye-slim-minimal
          - 3.2-bullseye-slim-qt
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.tag }}
          pull: ${{ github.event_name != 'pull_request' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE }}:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=${{ env.IMAGE }}:${{ matrix.tag }}
          cache-to: type=inline
          no-cache: ${{ github.event.schedule == '0 0 * * 0' || (github.event_name == 'workflow_dispatch' && inputs.no-cache) }}
