name: Build

on:
  push:
    branches:
      - main
  schedule: # Run everyday
    - cron: "0 0 * * *"

env:
  IMAGE: articulate/articulate-ruby

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.5-stretch-slim
          - 2.5-stretch-slim-minimal
          - 2.5-stretch-slim-qt
          - 2.6-stretch-slim
          - 2.6-stretch-slim-minimal
          - 2.7-buster-slim
          - 2.7-buster-slim-minimal
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - id: meta
        run: |
          TAGS="${{ env.IMAGE }}:${{ matrix.tag }}"
          [ -n "${{ matrix.latest }}" ] && TAGS="${TAGS},${{ env.IMAGE }}:latest"

          echo "::set-output name=tags::$TAGS"
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.tag }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=${{ env.IMAGE }}:${{ matrix.tag }}
          cache-to: type=inline
